/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Community { 'id' : bigint, 'name' : string }
export type ExternalBlob = Uint8Array;
export interface JoinRequest {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'communityId' : bigint,
  'user' : Principal,
  'timestamp' : bigint,
}
export type Language = { 'hindi' : null } |
  { 'gujarati' : null } |
  { 'english' : null };
export interface Post {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null },
  'content' : string,
  'communityId' : bigint,
  'author' : Principal,
  'timestamp' : bigint,
  'image' : [] | [ExternalBlob],
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'age' : bigint,
  'country' : string,
  'username' : string,
  'city' : string,
  'fullName' : string,
  'email' : string,
  'language' : Language,
  'address' : string,
  'village' : string,
  'mobile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveAllForCommunity' : ActorMethod<[bigint], undefined>,
  'approveJoinRequest' : ActorMethod<[bigint], undefined>,
  'approvePost' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearSession' : ActorMethod<[], undefined>,
  'createCommunity' : ActorMethod<[string], bigint>,
  'createPost' : ActorMethod<[string, bigint], bigint>,
  'createPostWithImage' : ActorMethod<[string, bigint, ExternalBlob], bigint>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'generateOTP' : ActorMethod<[string], string>,
  'getActiveSession' : ActorMethod<[], [] | [string]>,
  'getAllApprovedPosts' : ActorMethod<[bigint], Array<Post>>,
  'getAllCommunities' : ActorMethod<[], Array<Community>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommunityAdmins' : ActorMethod<[bigint], Array<Principal>>,
  'getCommunityMembers' : ActorMethod<[bigint], Array<Principal>>,
  'getPendingJoinRequests' : ActorMethod<[bigint], Array<JoinRequest>>,
  'getPendingPosts' : ActorMethod<[bigint], Array<Post>>,
  'getPost' : ActorMethod<[bigint], [] | [Post]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isCommunityAdmin' : ActorMethod<[bigint, Principal], boolean>,
  'isSessionActive' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'promoteToAdmin' : ActorMethod<[bigint, Principal], undefined>,
  'rejectJoinRequest' : ActorMethod<[bigint], undefined>,
  'rejectPost' : ActorMethod<[bigint], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'requestToJoinCommunity' : ActorMethod<[bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'verifyOTP' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];