/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({ 'pending' : IDL.Null, 'approved' : IDL.Null }),
  'content' : IDL.Text,
  'communityId' : IDL.Nat,
  'author' : IDL.Principal,
  'timestamp' : IDL.Nat,
  'image' : IDL.Opt(ExternalBlob),
});
export const Community = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const Language = IDL.Variant({
  'hindi' : IDL.Null,
  'gujarati' : IDL.Null,
  'english' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'country' : IDL.Text,
  'username' : IDL.Text,
  'city' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'language' : Language,
  'address' : IDL.Text,
  'village' : IDL.Text,
  'mobile' : IDL.Text,
});
export const JoinRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'communityId' : IDL.Nat,
  'user' : IDL.Principal,
  'timestamp' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveAllForCommunity' : IDL.Func([IDL.Nat], [], []),
  'approveJoinRequest' : IDL.Func([IDL.Nat], [], []),
  'approvePost' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearSession' : IDL.Func([], [], []),
  'createCommunity' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'createPostWithImage' : IDL.Func(
      [IDL.Text, IDL.Nat, ExternalBlob],
      [IDL.Nat],
      [],
    ),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'generateOTP' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getActiveSession' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getAllApprovedPosts' : IDL.Func([IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getAllCommunities' : IDL.Func([], [IDL.Vec(Community)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommunityAdmins' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getCommunityMembers' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getPendingJoinRequests' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(JoinRequest)],
      ['query'],
    ),
  'getPendingPosts' : IDL.Func([IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isCommunityAdmin' : IDL.Func(
      [IDL.Nat, IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'isSessionActive' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'promoteToAdmin' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'rejectJoinRequest' : IDL.Func([IDL.Nat], [], []),
  'rejectPost' : IDL.Func([IDL.Nat], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'requestToJoinCommunity' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({ 'pending' : IDL.Null, 'approved' : IDL.Null }),
    'content' : IDL.Text,
    'communityId' : IDL.Nat,
    'author' : IDL.Principal,
    'timestamp' : IDL.Nat,
    'image' : IDL.Opt(ExternalBlob),
  });
  const Community = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const Language = IDL.Variant({
    'hindi' : IDL.Null,
    'gujarati' : IDL.Null,
    'english' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'country' : IDL.Text,
    'username' : IDL.Text,
    'city' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'language' : Language,
    'address' : IDL.Text,
    'village' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const JoinRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'communityId' : IDL.Nat,
    'user' : IDL.Principal,
    'timestamp' : IDL.Nat,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveAllForCommunity' : IDL.Func([IDL.Nat], [], []),
    'approveJoinRequest' : IDL.Func([IDL.Nat], [], []),
    'approvePost' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearSession' : IDL.Func([], [], []),
    'createCommunity' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'createPostWithImage' : IDL.Func(
        [IDL.Text, IDL.Nat, ExternalBlob],
        [IDL.Nat],
        [],
      ),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'generateOTP' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getActiveSession' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getAllApprovedPosts' : IDL.Func([IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getAllCommunities' : IDL.Func([], [IDL.Vec(Community)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommunityAdmins' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getCommunityMembers' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getPendingJoinRequests' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(JoinRequest)],
        ['query'],
      ),
    'getPendingPosts' : IDL.Func([IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isCommunityAdmin' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'isSessionActive' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'promoteToAdmin' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'rejectJoinRequest' : IDL.Func([IDL.Nat], [], []),
    'rejectPost' : IDL.Func([IDL.Nat], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'requestToJoinCommunity' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };